## Numpy Array and Basics
learning numpy with **"Chai aur Code"** on YouTube  
-- @jkmloom

In [1]:
import numpy as np

### Creating Array from List

In [9]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(f"1D Array:\n{arr_1d}")

print(f"{'-'*12}")

arr_2d = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 0]])
print(f"2D Array:\n{arr_2d}")

1D Array:
[1 2 3 4 5]
------------
2D Array:
[[1 2 3 4 5]
 [6 7 8 9 0]]


### List vs Numpy Array

In [ ]:
py_list = [1, 2, 3, 4, 5]
print(f"Python list multiplication: {py_list * 2}") # 2 is a vector value

np_array = np.array(py_list)
print(f"Python array multiplication: {np_array * 2}") # 2 is a scaler value

Python list multiplication: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Python array multiplication: [ 2  4  6  8 10]


In [13]:
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("List Operation time", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("Numpy Array Operation time", time.time() - start)

List Operation time 0.12778210639953613
Numpy Array Operation time 0.007056713104248047


### Creating Array from Scratch

In [16]:
zeros = np.zeros((3, 4))
print(f"Zeros Array:\n{zeros}")

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
ones = np.ones((3, 4))
print(f"Ones Array:\n{ones}")

Ones Array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
# ones = np.ones((3, 4), dtype = int)
ones = np.ones((3, 4), int)
print(f"Ones Array:\n{ones}")

Ones Array:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [25]:
full = np.full((3, 3), 7)
print(f"Full Array:\n{full}")

Full Array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [31]:
# random in numpy is a class and has multiple methods
random = np.random.random((4, 4))
print(f"Random Array:\n{random}")
# random values variate between 0-1

Random Array:
[[0.7716638  0.35183133 0.00554918 0.15537399]
 [0.34692357 0.02175451 0.6421528  0.93366126]
 [0.75719705 0.87089413 0.73868596 0.28375765]
 [0.73097306 0.10946243 0.42200761 0.80507405]]


In [33]:
sequence = np.arange(0, 11, 2)
print(f"Sequence Array:\n{sequence}")

Sequence Array:
[ 0  2  4  6  8 10]


### Vector, Matrix, and Tensor

In [36]:
# matrix is 1 dimentional
vector = np.array([1, 2, 3, 4, 5])
print(f"Vector: {vector}")

Vector: [1 2 3 4 5]


In [37]:
# matrix is 2 dimentional
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(f"Matrix:\n{matrix}")

Matrix:
[[1 2 3]
 [4 5 6]]


In [40]:
# higher dimentional values
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print(f"Tensor:\n{tensor}")

Tensor:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [47]:
arr = np.array([[1, 2, 3],
                [4, 5, 6.8]])
print(f"Shape: {arr.shape}")
print(f"Dimention: {arr.ndim}")
print(f"Size: {arr.size}") # total no. of elements
print(f"Data Type: {arr.dtype}")


Shape: (2, 3)
Dimention: 2
Size: 6
Data Type: float64


### Array Reshaping

In [58]:
arr = np.arange(12)
print(f"Original Array: {arr}")

reshaped = arr.reshape((3, 4))
print(f"Reshaped Array:\n{reshaped}")

flattened = reshaped.flatten()
print(f"Flattened Array: {flattened}")

# ravel returns view, instead of copy
reveled = reshaped.ravel()
print(f"Reveled Array: {reveled}")

# transpose
transpose = reshaped.T
print(f"Transposed Array:\n{transpose}")

Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
