## Numpy Array Operations
@jkmloom

In [1]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Basic Slicing: {arr[2:7]}")
print(f"With Step: {arr[1:8:2]}")
print(f"Negative Indexing: {arr[-3]}")

Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative Indexing: 8


In [8]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(f"Specific Element: {arr_2d[1, 2]}") # [row, element]
print(f"Entire Row: {arr_2d[1]}")
print(f"Entire Column: {arr_2d[:, 1]}")

Specific Element: 6
Entire Row: [4 5 6]
Entire Column: [2 5 8]


### Sorting

In [11]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print(f"Sorted Array: {np.sort(unsorted)}")

arr_2d_unsorted = np.array([[3, 1], [1, 2], [3, 4]])
print(f"Sorted 2D Array by Column:\n{np.sort(arr_2d_unsorted, axis=0)}")
print(f"Sorted 2D Array by Rows:\n{np.sort(arr_2d_unsorted, axis=1)}")

Sorted Array: [1 1 2 3 4 5 6 9]
Sorted 2D Array by Column:
[[1 1]
 [3 2]
 [3 4]]
Sorted 2D Array by Rows:
[[1 3]
 [1 2]
 [3 4]]


### Filtering Array

In [12]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7 ,8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print(f"Even Numbers: {even_numbers}")

Even Numbers: [ 2  4  6  8 10]


### Filter with Mask

In [13]:
mask = numbers > 5 # mask is an expression
print(f"Numbers greater than 5: {numbers[mask]}")

Numbers greater than 5: [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [18]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print(f"np.where(): {numbers[where_result]}")

[1 3 5]
(array([5, 6, 7, 8, 9]),)
np.where(): [ 6  7  8  9 10]


In [25]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
condition_array = np.where(numbers > 5, numbers * 2, numbers)
# np.where(condition, operation, otherwise condition)
condition_array

array([ 1,  2,  3,  4,  5, 12, 14, 16, 18, 20])

In [27]:
condition_array = np.where(numbers > 5, "true", "false")
print(f"Array: {condition_array}")

Array: ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and Removing Data

In [29]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

combined = np.concatenate((arr_1, arr_2))
print(f"Combined Array: {combined}")

Combined Array: [1 2 3 4 5 6]


### Array Compatibility

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print(f"Compatibility Shapes: {a.shape == b.shape}")

Compatibility Shapes: True


In [35]:
original = np.array([[1, 2],
                    [3, 4]])
new_row = np.array([[5, 6]])

# np.vstack -> adds a row
with_new_row = np.vstack((original, new_row))
print(original, "\n")
print(with_new_row)

new_column = np.array([[7], [8]])
with_new_call = np.hstack((original, new_column))
print("\n", with_new_call)

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


In [37]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print(f"Array after deletion: {deleted}")

Array after deletion: [1 2 4 5]
