## DS: Numpy  
@jkmloom

In [1]:
# import numpy
import numpy as np

In [10]:
# normal array using numpy
print("1D Array:", np.array([1, 2, 3])) # 1d
print("\n2D Array:\n", np.array([[1, 2, 3], [4, 5, 6]])) # 2d
print("\n3D Array:\n", np.array([[[1, 2],[3, 4], [5, 6]], [[7, 8],  [9, 0], [1, 6]]]))

1D Array: [1 2 3]

2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [9 0]
  [1 6]]]


In [14]:
# array of zeros
print(np.zeros(10))
np.zeros(10, dtype=int)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros((4, 4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
# array of ones
np.ones((4, 4), int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [23]:
# array of 10 fives
print(np.ones(10) * 5)
np.ones(10, int) * 5

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [26]:
# array of integer from 10 to 100
np.arange(10, 101)

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
# array of even numbers from 0 to 50
np.arange(0, 51, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [28]:
# creating 3*3 matrix with values ranging from 0 to 8
np.arange(0, 9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# identity matrix: 3*3
print(np.eye(3)) # by default system returns float values
np.eye(3, dtype=int)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# generate a random number between 0-1
np.random.rand(1)

array([0.9550766])

In [ ]:
# 25 random numbers smapled from a standard normal distribution
# standard normal distribution: numpy.random.randn()
np.random.randn(25)

array([ 1.93091424, -0.67024275,  2.09072933,  0.57359255,  1.58125394,
        0.95964124, -0.12067499, -1.22099776,  1.39820531, -0.5025552 ,
        0.11422824,  0.0151868 , -1.33008143, -0.12772968, -0.07214185,
        1.02456839,  0.19483372,  0.86906102,  0.22557146,  0.89154522,
       -2.17500342,  0.1323922 , -0.21000726, -0.24776409,  0.04494531])

In [43]:
np.arange(1, 101).reshape(10, 10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [49]:
np.linspace(0.01, 1, 100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [55]:
np.linspace(10, 100, 9, dtype=int).reshape(3,3)

array([[ 10,  21,  32],
       [ 43,  55,  66],
       [ 77,  88, 100]])

In [59]:
matrix = np.arange(1, 26).reshape(5, 5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
matrix[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [70]:
print(matrix[3, 4])
matrix[3, -1]

20


np.int64(20)

In [73]:
matrix[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [74]:
matrix[4]

array([21, 22, 23, 24, 25])

In [75]:
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [76]:
matrix[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [78]:
print(matrix.sum())

325


In [81]:
print(np.sum(matrix))
np.sum(matrix)

325


np.int64(325)

In [84]:
# sum of all the columns
matrix.sum(axis=0)

array([55, 60, 65, 70, 75])

In [85]:
print(np.sum(matrix, axis=0))

[55 60 65 70 75]
